name: ${project.name}
main: com.gmail.sharpcastle33.CivEnchant
version: ${project.version}
commands:
   givecivenchant:
      description: (OP ONLY) debug command for setting an enchant on an item
      usage: with an item in main hand /gce <enchant> <level>
      aliases: [ gce ]
   givesafecivenchant:
      description: (OP ONLY) debug command for setting a safe enchant on an item
      usage: with an item in main hand /gsce <enchant> <level>
      permission: civenchant.give.safe
      aliases: [ gsce ]
   listcivenchants:
      description: (OP ONLY) debug command to list all enchantments
      usage: /lce
      permission: civenchant.list
      aliases: [ lce ]
   civenchantinfo:
      description: Gives information on the usage of each enchant on an item in your main hand
      usage: with item in main hand /cei
      aliases: [ cei ]
   updateconstants:
      description: Updates the values in the CONSTANTS class to whatever values that are mentioned in the civenchantconfig.txt file. 
      usage: /udc
      aliases: [ udc ]   
   displayconstants:
      description: Displays current values in the CONSTANTS class
      usage: /displayc
      aliases: [ displayc ]
